import{r as e}from"./assets/rolldown-runtime-hePW80VL.js";import{a as t,i as n,n as r,o as i,r as a,t as o}from"./assets/vendor-BT2DXJVw.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),t.credentials=e.crossOrigin===`use-credentials`?`include`:e.crossOrigin===`anonymous`?`omit`:`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var s=document.querySelector(`.header-menu-btn`),c=document.querySelector(`#mob-menu`),l=document.querySelector(`.mob-menu-close-btn`);s.addEventListener(`click`,u),l.addEventListener(`click`,d);function u(){c.classList.add(`is-open`),document.body.classList.add(`scroll-locked`)}function d(){c.classList.remove(`is-open`),document.body.classList.remove(`scroll-locked`)}document.querySelectorAll(`.mob-menu-logo, .mob-menu-nav-link, .mob-menu-book-btn`).forEach(e=>{e.addEventListener(`click`,d)});var f=e(i(),1),p=document.querySelector(`.loader`);function m(){p.classList.remove(`is-hidden`)}function h(){p.classList.add(`is-hidden`)}t.defaults.baseURL=`https://wedding-photographer.b.goit.study/api`;var g=document.querySelector(`#modal-succsess`),_=document.querySelector(`.modal-close-btn`),v=document.querySelector(`.form`);_.addEventListener(`click`,x),g.addEventListener(`click`,C),document.addEventListener(`keydown`,S),v.addEventListener(`submit`,y);function y(e){e.preventDefault(),m();let n=new FormData(e.target),r=Object.fromEntries(n);t.post(`/orders`,r).then(()=>{h(),b(),v.reset()}).catch(()=>{h(),f.default.error({message:`Something went wrong. Please try again.`})})}function b(){g.classList.add(`is-open`),document.body.classList.add(`scroll-locked`)}function x(){g.classList.remove(`is-open`),document.body.classList.remove(`scroll-locked`)}function S(e){e.key===`Escape`&&x()}function C(e){e.target===e.currentTarget&&x()}var w=[{text:`Your feedback text goes here.`,author:`Alex and Maria`},{text:`Another couple’s review goes here.`,author:`James and Olivia`},{text:`A third review goes here.`,author:`Noah and Emma`}],T=document.querySelector(`.feedbacks-list`),E=document.querySelector(`.feedbacks-dots`),D=document.querySelector(`.feedbacks-button-prev`),O=document.querySelector(`.feedbacks-button-next`);if(T&&E&&D&&O){T.innerHTML=w.map(({text:e,author:t})=>`
        <li class="feedbacks-item">
          <article class="feedbacks-card">
            <p class="feedbacks-text">${e}</p>
            <p class="feedbacks-author">${t}</p>
          </article>
        </li>
      `).join(``),new n(`.feedbacks-slider`,{modules:[r,o,a],wrapperClass:`feedbacks-list`,slideClass:`feedbacks-item`,slidesPerView:1,spaceBetween:0,speed:250,breakpoints:{768:{slidesPerView:3}},grabCursor:!0,allowTouchMove:!0,keyboard:{enabled:!0,onlyInViewport:!0},navigation:{prevEl:D,nextEl:O},pagination:{el:E,clickable:!0,bulletClass:`feedbacks-dot`,bulletActiveClass:`is-active`,renderBullet(e,t){return`
          <button
            class="${t}"
            type="button"
            aria-label="Go to feedback ${e+1}"
          ></button>
        `}},watchOverflow:!0,on:{init(){e(this)},slideChange(){e(this)},lock(){e(this)},unlock(){e(this)}}});function e(e){D.disabled=e.isBeginning||e.isLocked,O.disabled=e.isEnd||e.isLocked}}document.addEventListener(`DOMContentLoaded`,()=>{let e=document.querySelectorAll(`.faq-item`);e.forEach(t=>{let n=t.querySelector(`.faq-question`);n.addEventListener(`click`,()=>{let r=t.classList.contains(`active`);e.forEach(e=>{e.classList.remove(`active`),e.querySelector(`.faq-question`).setAttribute(`aria-expanded`,`false`)}),r||(t.classList.add(`active`),n.setAttribute(`aria-expanded`,`true`))})})});
//# sourceMappingURL=index.js.map