import{i as e,n as t,r as n,t as r}from"./assets/vendor-B77a18gK.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),t.credentials=e.crossOrigin===`use-credentials`?`include`:e.crossOrigin===`anonymous`?`omit`:`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var i=document.querySelector(`.header-menu-btn`),a=document.querySelector(`#mob-menu`),o=document.querySelector(`.mob-menu-close-btn`);i.addEventListener(`click`,s),o.addEventListener(`click`,c);function s(){a.classList.add(`is-open`),document.body.classList.add(`scroll-locked`)}function c(){a.classList.remove(`is-open`),document.body.classList.remove(`scroll-locked`)}document.querySelectorAll(`.mob-menu-logo, .mob-menu-nav-link, .mob-menu-book-btn`).forEach(e=>{e.addEventListener(`click`,c)});var l=[{text:`Your feedback text goes here.`,author:`Alex and Maria`},{text:`Another couple’s review goes here.`,author:`James and Olivia`},{text:`A third review goes here.`,author:`Noah and Emma`}],u=document.querySelector(`.feedbacks-list`),d=document.querySelector(`.feedbacks-dots`),f=document.querySelector(`.feedbacks-button-prev`),p=document.querySelector(`.feedbacks-button-next`);if(u&&d&&f&&p){u.innerHTML=l.map(({text:e,author:t})=>`
        <li class="feedbacks-item">
          <article class="feedbacks-card">
            <p class="feedbacks-text">${e}</p>
            <p class="feedbacks-author">${t}</p>
          </article>
        </li>
      `).join(``),new e(`.feedbacks-slider`,{modules:[t,r,n],wrapperClass:`feedbacks-list`,slideClass:`feedbacks-item`,slidesPerView:1,spaceBetween:0,speed:250,breakpoints:{768:{slidesPerView:3}},grabCursor:!0,allowTouchMove:!0,keyboard:{enabled:!0,onlyInViewport:!0},navigation:{prevEl:f,nextEl:p},pagination:{el:d,clickable:!0,bulletClass:`feedbacks-dot`,bulletActiveClass:`is-active`,renderBullet(e,t){return`
          <button
            class="${t}"
            type="button"
            aria-label="Go to feedback ${e+1}"
          ></button>
        `}},watchOverflow:!0,on:{init(){i(this)},slideChange(){i(this)},lock(){i(this)},unlock(){i(this)}}});function i(e){f.disabled=e.isBeginning||e.isLocked,p.disabled=e.isEnd||e.isLocked}}document.addEventListener(`DOMContentLoaded`,()=>{let e=document.querySelectorAll(`.faq-item`);e.forEach(t=>{let n=t.querySelector(`.faq-question`);n.addEventListener(`click`,()=>{let r=t.classList.contains(`active`);e.forEach(e=>{e.classList.remove(`active`),e.querySelector(`.faq-question`).setAttribute(`aria-expanded`,`false`)}),r||(t.classList.add(`active`),n.setAttribute(`aria-expanded`,`true`))})})});
//# sourceMappingURL=index.js.map